//@ui5-bundle testplugin/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"testplugin/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent"],function(e){"use strict";return e.extend("testplugin.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);console.log("ccaa");setTimeout(()=>{sap.m.MessageToast.show("secondPlugIn")},2e3);this._oShellContainer=jQuery.sap.getObject("sap.ushell.Container");const t=this._oShellContainer.getRenderer();if(!t)return sap.m.MessageToast.show("not find shell Container");t.addHeaderEndItem({id:"myTestButton",icon:"sap-icon://hello-world",text:"hello world",press:()=>{sap.m.MessageToast.show("hello world22")}},true)}})});
},
	"testplugin/i18n/i18n.properties":'# This is the resource bundle for testplugin\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=testplugin\n\n#YDES: Application description\nappDescription=A Fiori application.\n#XTIT: Main view title\ntitle=testplugin\n\nflpTitle=tile\n\nflpSubtitle=tile\n',
	"testplugin/manifest.json":'{"_version":"1.49.0","sap.app":{"id":"testplugin","type":"component","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.8.6","toolsId":"f6be61d7-b86a-4971-bf91-693afbd1d7ea"},"crossNavigation":{"inbounds":{"testplugin-inbound":{"signature":{"parameters":{},"additionalParameters":"allowed"},"semanticObject":"Shell","action":"plugin","title":"{{flpTitle}}","subTitle":"{{flpSubtitle}}","icon":"","hideLauncher":true}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.110.1","libs":{"sap.m":{},"sap.ui.core":{},"sap.f":{},"sap.suite.ui.generic.template":{},"sap.ui.comp":{},"sap.ui.generic.app":{},"sap.ui.table":{},"sap.ushell":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"testplugin.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]}},"sap.cloud":{"public":true,"service":"testPlugin"},"sap.flp":{"type":"plugin"}}'
}});
